import {
  Utensils,
  Sparkles,
  Home,
  Laptop,
  SmartphoneCharging,
  Briefcase,
  Computer,
  Monitor,
  Tablet,
  Smartphone,
  LayoutGrid,
  Tags,
  Snowflake,
  Bike,
  Armchair,
  BedDouble, 
  LoaderPinwheel,
  ThermometerSnowflake,
  WashingMachine,
  Sofa,
  SquareM,
  AudioLines,
  Tv,
  Microchip,
} from "lucide-react";

export const categories = [
  {
    id: 0,
    name: "Todos",
    label: "Todos",
    color: "bg-airbnb-purple",
    icon: "LayoutGrid",
  },
  {
    id: 1,
    name: "Kitchen",
    label: "Cocina",
    color: "bg-airbnb-peach",
    icon: Utensils,
  },
  {
    id: 2,
    name: "Cleaning",
    label: "Limpieza",
    color: "bg-airbnb-blue",
    icon: Sparkles,
  },
  { id: 3, name: "Home", label: "Hogar", color: "bg-airbnb-green", icon: Home },
  {
    id: 4,
    name: "Electronics",
    label: "Electronica",
    color: "bg-airbnb-yellow",
    icon: Laptop,
  },
  {
    id: 5,
    name: "Smart Home",
    label: "Smart Home",
    color: "bg-airbnb-purple",
    icon: SmartphoneCharging,
  },
  {
    id: 6,
    name: "Office",
    label: "Oficina",
    color: "bg-airbnb-pink",
    icon: Briefcase,
  },
  {
    id: 7,
    name: "Computers",
    label: "Computadoras",
    color: "bg-airbnb-peach",
    icon: Computer,
  },
  {
    id: 8,
    name: "Monitors",
    label: "Monitores",
    color: "bg-airbnb-blue",
    icon: Monitor,
  },
  {
    id: 9,
    name: "Tablets",
    label: "Tabletas",
    color: "bg-airbnb-green",
    icon: Tablet,
  },
  {
    id: 10,
    name: "Smartphones",
    label: "Celulares",
    color: "bg-airbnb-yellow",
    icon: Smartphone,
  },
];
