import {
  Utensils,
  Sparkles,
  Home,
  Laptop,
  SmartphoneCharging,
  Briefcase,
  Computer,
  Monitor,
  Tablet,
  Smartphone,
  LayoutGrid,
  Tags,
  Snowflake,
  Bike,
  Armchair,
  BedDouble,
  LoaderPinwheel,
  ThermometerSnowflake,
  WashingMachine,
  Sofa,
  SquareM,
  AudioLines,
  AudioWaveform,
  Tv,
  Microchip,
  ChefHat,
  Refrigerator,
  SunSnow,
} from "lucide-react";

export const categoryIcons = {
  "0000": LayoutGrid,
  "001": Snowflake,
  "017": Bike,
  "021": Computer,
  "026": Armchair,
  "028": AudioLines,
  "031": ChefHat,
  "032": BedDouble,
  "056": ThermometerSnowflake,
  "062": ChefHat,
  "064": Refrigerator,
  "073": WashingMachine,
  "075": Sofa,
  "093": SquareM,
  "100": BedDouble,
  "106": AudioWaveform,
  "121": Tv,
  "123": Smartphone,
  "130": Home,
  "200": Microchip,
  "999": Tags,
};
